// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"dependency_injection_tut/event"
	"dependency_injection_tut/greeter"
	"dependency_injection_tut/message"
)

// Injectors from wire.go:

func InitializeEvent() event.Event {
	messageMessage := message.NewMessage()
	greeterGreeter := greeter.NewGreeter(messageMessage)
	eventEvent := event.NewEvent(greeterGreeter)
	return eventEvent
}
